<a href="https://colab.research.google.com/github/MariMukai/CarePlus_Sprint3/blob/main/AULA_AMOSTRAGEM_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd
import numpy as np

#criando um dataframe ficticio
np.random.seed (23) #garante a reprodução do experimento
n=10000 #Quantidade de clientes que queremos gerar dados ficticios

df=pd.DataFrame({
    "ID":range(1,n+1),
    "Idade": np.random.randint(18,65,n),
    "Renda": (np.random.uniform(2000.0, 30000.0,n).round(2)),
    "Regiao": np.random.choice(["Norte", "Sul", "Leste", "Oeste"], n)
})

print(df.head(50))

    ID  Idade     Renda Regiao
0    1     37  12130.54    Sul
1    2     56  20674.66    Sul
2    3     58  20874.69    Sul
3    4     27   5454.45  Oeste
4    5     58  13978.69    Sul
5    6     49  24899.76  Leste
6    7     63  18621.13  Leste
7    8     30   8635.84  Norte
8    9     45  18655.89  Oeste
9   10     57  11344.33  Norte
10  11     44  19972.16  Leste
11  12     43   4960.00  Norte
12  13     24  28501.56  Leste
13  14     63  16532.97  Leste
14  15     30   7062.31  Oeste
15  16     20  21018.76  Norte
16  17     29   9146.08  Oeste
17  18     39  13427.80    Sul
18  19     23  22783.54  Oeste
19  20     18  18685.19  Norte
20  21     30   3246.77  Norte
21  22     39  24064.86  Leste
22  23     59  21676.91    Sul
23  24     33   2809.42  Leste
24  25     44   5853.10    Sul
25  26     37   3444.77  Leste
26  27     51   8130.77  Oeste
27  28     57  21404.82  Norte
28  29     33  19858.98  Leste
29  30     54  24026.53  Oeste
30  31     19   6270.26  Norte
31  32     19  12021.56  Norte
32  33     61  16243.40  Leste
33  34     33   8017.92  Norte
34  35     40  14524.62  Oeste
35  36     57  23758.08  Leste
36  37     37  28989.94  Oeste
37  38     43   9006.25  Oeste
38  39     20  12966.06  Oeste
39  40     28   6578.70  Oeste
40  41     62  16452.05  Norte
41  42     53  15655.60  Leste
42  43     50  17431.23  Leste
43  44     31   9804.38  Oeste
44  45     40  16845.04  Norte
45  46     56   7440.68  Norte
46  47     49  22163.55  Leste
47  48     48  21812.10  Oeste
48  49     32  13212.12    Sul
49  50     18  10628.32    Sul

In [7]:
#AMOSTRAGEM ALEATORIA SIMPLES
amostragem_simples = df.sample(n=1000, random_state=33) #RANDOM STATE TEM O  MESMO PAPEL DO
amostragem_simples.head()

        ID  Idade     Renda Regiao
5672  5673     18   9856.73    Sul
3346  3347     59  23309.21  Norte
5867  5868     37   4622.90    Sul
2322  2323     51   6056.16  Leste
5233  5234     44  26109.14  Norte

In [8]:
#AMOSTRAGEM ALEATORIA SISTEMATICA:
intervalo =  np.random.randint(1, 50) #gera intervalo com base na quantidade de registros arrendondando p baixo
amostra_sistematica = df.iloc[::intervalo,:]
amostra_sistematica.head()

    ID  Idade     Renda Regiao
0    1     37  12130.54    Sul
21  22     39  24064.86  Leste
42  43     50  17431.23  Leste
63  64     39  12688.36    Sul
84  85     55  21460.54  Oeste